config/routes.rb
require "sidekiq/web"
Aligator::Application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  devise_for :users
  resources :users, only: [:index, :show]
  resources :links do
    get 'search' => 'search#search', on: :collection
    get 'search/suggest_tags' => 'search#suggest_tags', on: :collection
    put "like", to: "links#vote_up", on: :member
    resources :comments, only: [:create, :destroy, :index]
    resources :tags,  only: [:create, :new, :index, :destroy], param: :name
  end
  resources :activities, only: [:index]
  resources :subscriptions, only: [:create]
  root 'links#index'

  mount Sidekiq::Web, at: '/sidekiq'

end

app/models/link.rb
require "addressable/uri"

class Link < ActiveRecord::Base
  include Tire::Model::Search
  include Tire::Model::Callbacks
  include PublicActivity::Model
  has_one :content
  has_many :comments, dependent: :destroy

  after_touch() { tire.update_index }

  belongs_to :user

  validates :url, url: true
  validates :title, presence: true
  acts_as_taggable_on :tags
  acts_as_votable
  default_scope { order('created_at DESC') }
  delegate :email, to: :user, prefix: true, allow_nil: true

  tire.settings analysis: {
    analyzer: {
      full_title: {
        filter: %w(standard lowercase asciifolding),
        type: 'custom',
        tokenizer: 'standard'
      },
      partial_title: {
        filter: %w(standard lowercase asciifolding title_ngram),
        type: 'custom',
        tokenizer: 'standard'
      }
    },
    filter: {
      title_ngram: {
        side: 'front',
        max_gram: 20,
        min_gram: 2,
        type: 'edgeNGram',
        token_chars: %w(letter digit whitespace)
      }
    }
  } do
    tire.mapping do
      indexes :title,
              type: 'string', boost: 10,
              search_analyzer: 'full_title',
              index_analyzer: 'partial_title'
      indexes :comments, type: 'object'
      indexes :content, type: 'object'
      indexes :tag_list, as: 'tag_list.join(", ")'
    end
  end

  def to_indexed_json
    to_json(include: { comments: { only: [:content] },
                       content:  { only: [:github_readme] }
                      },
            methods: :tag_list)
  end

  def search(query)
    query do
      string term, default_field: 'title', default_operator: 'AND'
      match :title, term, type: 'phrase_prefix', max_expansions: 10
    end
  end
  
  def parse(data, user)
    parsed_data = {}
    parsed_data[:url] = data.split.select do |url|
      url.match(/^((http?:\/\/)|(ftp:\/\/))?([a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{0,10}(([0-9]{1,5})?\/.*)?$)/)
    end

    if URI.extract(data).empty?
      parsed_data[:url] = parsed_data[:url].join(' ').prepend('http://')
      data.slice!(parsed_data[:url].gsub('http://', ''))
    else
      parsed_data[:url] = URI.extract(data).join(' ')
      data.slice!(parsed_data[:url])
    end
    data.slice!(parsed_data[:url])
    parsed_data[:tag_list]  = data.scan(/(\#\S+)/).join(' ').gsub(/\#/, '')
    parsed_data[:title] = data.gsub(/(\#\S+)/, '').strip
    parsed_data[:user]  = user
    return parsed_data
  end

  def save_link(link_data = {})
    return false if link_data.blank?
    assign_attributes(link_data)
    save
  end
  
  def parse_and_save(data, user = nil)
    parsed_data = parse(data, user)
    save_link(parsed_data)
  end

  def screenshot_exist?
    File.exist? screenshot_path
  end

  def screenshot_root
    "#{ENV['SCREENSHOT_ROOT']}link_#{self.id}.png"
  end

  def screenshot_path
    "#{ENV['SCREENSHOT_PATH']}link_#{self.id}.png"
  end

  def http?
    @http ||= url.starts_with?('http')
  end

  def scheme_with_http?
    @scheme ||= url_with_scheme.starts_with?('http')
  end

  def url_with_scheme
    @url ||=
      if url.starts_with?('http://', 'https://', 'ftp://', 'mailto', 'ldap')
        url
      else
        "http://#{url}"
      end
  end

  def video_embed?
    /be.com\/embed\// =~ url
  end

  def ftp?
    url.starts_with?('ftp')
  end

  def content_exist?
    self.content.content.present?
  end

  def github_exist?
    true if %r{.*github.com\/.*} =~ url
  end

  def added_by
    user_email || "Guest"
  end

  def number_of_likes
    get_upvotes.size
  end


  def set_added_from_web
    self.added_from = "web"
  end

  def set_added_from_email
    self.added_from = "email"
  end

  def last_modified
    uri = URI(url)
    res = Net::HTTP.get_response(uri)
    res.get_fields("Last-Modified")
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  helper_method :searched_by?
  # GET /links
  # GET /links.json
  def index
    @activities = PublicActivity::Activity.find(:all, order: "created_at desc", limit: 10)
    if params[:tag]
      @links = Link.tagged_with(params[:tag]).decorate
      searched_by("tag", params[:tag])
    elsif params[:user]
      user = User.find_by(email: params[:user])
      @links = user.links.decorate
      searched_by("user", user.email)
    else
      @links = Link.all.decorate
    end

    @link = Link.new
    respond_to do |format|
      format.html
      format.json { render json: @links }
      format.rss
    end
  end
  # GET /links/1
  # GET /links/1.json
  def show
    @comment = current_user.comments.build(params[:link_id]) if signed_in?
    @comments = @link.comments
    respond_to do |format|
      format.html
      format.json { render json: @link }
    end
  end
  # GET /links/new
  # GET /links/1/edit
  def edit
  end
  # POST /links
  # POST /links.json
  def create
    @link = Link.new
    respond_to do |format|
      @link.set_added_from_web
      if @link.parse_and_save(params[:link][:link_data], current_user)
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render json: @link }
        ActivitiesCreator.create_link_activity(@link)
        if @link.github_exist?
          GithubReadmeWorker.perform_async(@link.id)
        else
          FetchContentPageWorker.perform_async(@link.id)
        end
        ScreenshotWorker.perform_async(@link.id)
        SubscribesNotificationWorker.perform_async(@link.id) if current_user.present?
      else
        @links = Link.all.decorate
        format.html { render action: 'index', notice: 'Link was not added' }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url }
      format.json { head :no_content }
    end
  end

  def vote_up
    @link = Link.find(params[:id])
    return redirect_to @link unless current_user
    if (current_user.voted_as_when_voted_for @link) == false
      @link.liked_by current_user
    elsif (current_user.voted_as_when_voted_for @link).nil?
      @link.liked_by current_user
    else
      @link.downvote_from current_user
    end
    redirect_to @link
  end

  private

  def searched_by(by, name)
    if by == "tag"
      @searched_by = "Links tagged with ##{name}"
    else
      @searched_by = "Links added by #{name}"
    end
  end
  # Use callbacks to share common setup or constraints between actions.
  def set_link
    @link = Link.find(params[:id]).decorate
  end

  # Never trust parameters from the scary internet,
  # only allow the white list through.
  def link_params
    params.require(:link).permit(:url, :title, :tag_list, :link_data,
                                 :gh_readme, :content, :link_id, :user_id)
  end
end

app/helpers/links_helper.rb
module LinksHelper
  include ActsAsTaggableOn::TagsHelper
end

app/views/links/edit.html.erb
<% provide(:title, "Edit") %>
<h1>Editing link</h1>

<%= simple_form_for @link do |f| %>
  <%= render 'shared/error_form', object: f.object %>
  <%= f.input :url, label: 'Type your link url:' %>
  <%= f.input :tag_list, label: 'Type tags' %>
  <%= f.input :title, label: 'Type title:' %>
  <%= f.button :submit %>
<% end %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', root_path %>

app/views/links/index.html.erb
<div ng-controller="LinksController">
  <div ng-if= "linkUpdated">
    <div class="alert alert-success" >
      <button type="button" class="close" data-dismiss="alert"> &times;</button>
      Link was successfuly added!
    </div>
  </div>

  <%= link_to links_path(:rss) do %>
    <i class="fa fa-rss fa-2x"></i>
  <% end %>

  <h1><%= link_to "Aligator", root_path %></h1>
  <div id="left_content">
  <form ng-submit="createLink()">
    <fieldset>
      <div class="control-group" ng-class="{ 'error': errors }" >
        <div class="controls">
          <div class="input-append">
            <input id="linkInput" type="text" ng-model='model' autocomplete placeholder="Enter link data">
            <button type="submit" class="btn btn-primary">Add</button>
          </div>
        </div>
        <div ng-if= "errors">
          <p class="help-block error" > {{errors}} </p>
        </div>
      </div>

      <h5>Add link by typing url #hash and 'title' in either order like: #tag1
        http://www.page.com #tag2 #tag3 'Title of this page' </h5>
    </fieldset>
  </form>
  <div class="tagged_with">
    <%= @searched_by %>
  </div>
  <ul>
    <% if @searched_by.present? %>
      <% @links.each do |link| %>
        <li class="li-without-decoration">
          <%= link.id %>
          <%= link_to link.title, link.url_with_scheme %>
          (<%= link_to link.host, link.host_with_scheme %>)
          | <%= link_to 'Show', link_path(link.id) %>
        <div class = "description">
          <% link.tag_list.each do |tag| %>
            <div class="ng-scope">
              <%= link_to "##{tag}", links_path(tag: tag) %>
              <a class="fa fa-rss fa-1x" ng-href ="links.rss?tagged_with=<%= tag %>"></a>
            </div>
          <% end %>
          <div class="added_by">
            Added by <%= link.show_link_owner %>, <%= link.created_at_status %> ago.
          </div>
          Liked by <%= link.number_of_likes %> ppl <i class="fa fa-thumbs-o-up"></i>s
        </div>
      </li>
    <% end %>
  <% else %>
    <li ng-repeat="link in links">
      {{link.id}}.
      <a ng-href ="{{link.urlWithScheme}}">{{link.title}}</a>
      (<a ng-href ="{{link.hostWithScheme}}">{{link.host}}</a>)
      | <%= link_to 'Show',"#{links_path()}/{{link.id}}" %>
    <div class = "description">
      <div ng-repeat="tag in link.tagList">
        <%= link_to "{{tag}}","#{links_path()}/?tag={{tag}}" %>
        <a class="fa fa-rss fa-1x" ng-href ="links.rss?tagged_with={{tag}}"></a>
      </div>
      <div class="added_by" ng-hide="link.addedBy ==='Guest'">
        Added by <%= link_to '{{link.addedBy}}',"#{links_path()}/?user={{link.addedBy}}"%>, {{link.createdAtStatus}} ago.
      </div>
      <div class="added_by" ng-show="link.addedBy ==='Guest'">
        Added by Guest, {{link.createdAtStatus}} ago.
      </div>
      Liked by {{link.numberOfLikes}} ppl <i class="fa fa-thumbs-o-up"></i>s
    </div>
  </li>
<% end %>
</ul>
  </div>
  <% if signed_in? %>
  <div id ="right_content">
    <% @activities.each do |activity| %>
      <div class="activity">
        <%= activity.decorate.display_activity_owner %>
        <%= render_activity activity %>
      </div>
    <% end %>
  </div>
<% end%>
</div>

app/views/links/show.html.erb
<% provide(:title, "Aligator -> #{@link.title}") %>

<script>
  window.Id = <%= @link.id %>
</script>
<h3><%= @link.title %></h3><h4><%= @link.link_to_host %></h4>
<p>
  <%= link_to @link.url, @link.url_with_scheme ,class: "link" %>
</p>
<p>
  <strong>Updated at:</strong>
  <%= @link.created_at_status_detailed %>
  <strong>Added by:</strong>
  <%= @link.show_link_owner %>
  <br />
  <strong>Number of like's <i class="fa fa-thumbs-o-up"></i></strong>
  <%= @link.get_upvotes.size %>
  <br />
<%= button_to('Vote for this link!', like_link_path(@link), method: :put) %>
<%= @link.user.decorate.subscribe_user %>
<%= button_to 'New Tag', new_link_tag_path(@link.id), method: :get %>

</p>
  <%= @link.video_play %>
  <%= @link.show_screenshot %>
  <%= @link.content %>
<div class="row">
  <div class="span10">
    <div ng-controller="CommentController">
      <div ng-if= "commentUpdated">
        <div class="alert alert-success" >
          <button type="button" class="close" data-dismiss="alert"> &times;</button>
          Comment was successfuly added!
        </div>
      </div>
      Comments({{comments.length}}):
      <ol class="comments">
        <div ng-repeat="comment in comments">
          <li>
            <span class="content">
              {{comment.content}}
            </span>
            <span class="timestamp">
            Posted {{comment.created}} ago
            by {{comment.owner_email}}
            </span>
          </li>
        </div>
      </ol>
      <% if signed_in? %>
      <section>
        <form ng-submit="createComment()">
          <fieldset>
            <div class="control-group" ng-class="{ 'error': errors }" >
              <textarea rows="3" ng-model='comment.content' placeholder="Enter Comment"></textarea>
              <button type="submit" class="btn btn-primary">Add</button>
              <div ng-if= "errors">
                <p class="help-block error" >
                  {{errors}}
                </p>
              </div>
            </div>
          </fieldset>
        </form>
      </section>
    </div>
    <% else %>
    <div class="sign_in">
      <%= link_to "Sign in", new_user_session_path%> to add comment.
    </div>
    <% end %>
    <br>
    <%= link_to 'Edit', edit_link_path(@link) %> |
    <%= link_to 'Home', root_path %> |
    <%= link_to 'Tag List', link_tags_path(@link) %>
  </div>
  <div>
</div>