config/routes.rb
require "sidekiq/web"
Aligator::Application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  devise_for :users
  resources :users, only: [:index, :show]
  resources :links do
    get 'search' => 'search#search', on: :collection
    get 'search/suggest_tags' => 'search#suggest_tags', on: :collection
    put "like", to: "links#vote_up", on: :member
    resources :comments, only: [:create, :destroy, :index]
    resources :tags,  only: [:create, :new, :index, :destroy], param: :name
  end
  resources :activities, only: [:index]
  resources :subscriptions, only: [:create]
  root 'links#index'

  mount Sidekiq::Web, at: '/sidekiq'

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @link = Link.find(params[:link_id])
  end

  def destroy
    @link = Link.find(params[:link_id])
    @link.tag_list.remove(params[:name])
    respond_to do |format|
      if @link.save
        format.html { redirect_to link_tags_path(@link), notice: 'Tag was successfully deleted!' }
      else
        format.html { redirect_to link_tags_path(@link) }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  def new
    @link = Link.find(params[:link_id]).decorate
    @tag =  ActsAsTaggableOn::Tag.new
  end

  def create
    link = Link.find(params[:link_id])
    tag_name = params[:acts_as_taggable_on_tag].nil? ? " " : params[:acts_as_taggable_on_tag][:name]
    if tag_name.present? && link.tag_list.add(tag_name) && link.save
      redirect_to new_link_tag_path(link.id), notice: 'Tag was successfully added.'
    else
      redirect_to new_link_tag_path(link.id), alert: 'Tag was not successfully added.
        Please enter a tag name.'
    end
  end
end

app/views/tags/index.html.erb
<br />
<div id="tags">
  <ol>
    <% @link.tag_list.each do |tag| %>
      <li>
        <%= tag %>
        <%= link_to 'Delete', link_tag_path(@link, name: tag), method: 'delete', data: { confirm: 'Are you sure?' } %> <br />
      </li>
    <% end %>
  </ol>
</div>
<br />
<%= link_to 'Back', link_path(@link) %>

app/views/tags/new.html.erb
<p>
  <h3>Add tag to <%= @link.title %></h3>
  <h5><%= @link.url %></h5>
</p>
<p>
  <%= @link.show_tags %>
</p>
<hr>
<p>
  <h2>New tag</h2>
  <%= simple_form_for @tag, url: link_tags_path do |f| %>
    <%= f.input :name, label: 'Tag name' %>
    <%= f.button :submit %>
  <% end %>
</p>

<%= link_to 'Back', link_path(@link) %>