config/routes.rb
require "sidekiq/web"
Aligator::Application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  devise_for :users
  resources :users, only: [:index, :show]
  resources :links do
    get 'search' => 'search#search', on: :collection
    get 'search/suggest_tags' => 'search#suggest_tags', on: :collection
    put "like", to: "links#vote_up", on: :member
    resources :comments, only: [:create, :destroy, :index]
    resources :tags,  only: [:create, :new, :index, :destroy], param: :name
  end
  resources :activities, only: [:index]
  resources :subscriptions, only: [:create]
  root 'links#index'

  mount Sidekiq::Web, at: '/sidekiq'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app='Aligator'>
  <head>
    <title><%= yield(:title) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application"%>
    <%= csrf_meta_tags %>
    <script>
      window.Base = "<%= ENV['BASE_PATH']%>";
    </script>
  </head>
  <body>
    <p class="navbar-text pull-right">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Search Links', search_links_path, class: 'navbar-link' %> |
        <%= link_to 'Edit profile', edit_user_registration_path, class: 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, class: 'navbar-link'  %>
      <% else %>
        <%= link_to 'Search Links', search_links_path, class: 'navbar-link'  %> |
        <%= link_to "Sign up", new_user_registration_path, class: 'navbar-link'  %> |
        <%= link_to "Login", new_user_session_path, class: 'navbar-link'  %>
      <% end %>
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
  </body>
</html>